### ISSUE TITLE
Looks like -verifySSL is not doing anything

### ISSUE THREAD

**Issue by herrbpl** [pteich/elastic-query-export#22]
Cannot query elasticsearch instance where certificate is self-signed ad-or does not match hostname. Specifying -verifySSL false or 
-verifySSL 0 or just without parameter, seems to have no effect, still get message:

```log
 Error connecting to ElasticSearch: health check timeout: Head "https://x.y.z:9200": x509: certificate is valid for a.b.c, not x.y.z: no Elasticsearch node available
```

**Comment by herrbpl** [comment]
In fact, specifying `-verifySSL` seems to stop processing command line arguments at all. If you specify this flag before `-c url`, application tries to connect to localhost:9200..

**Comment by pteich** [comment]
You need to pass `--verifySSL=true`  or `--verifySSL=false`  to toggle verifying SSL certificates or not. In the end this sets the "skip verify" of provided certificates in the HTTP client.
I will improve the docs for pointing this out :)
