### ISSUE TITLE
Integer numeric fields (long type in mappings) exported as floats

### ISSUE THREAD

**Issue by brablc** [pteich/elastic-query-export#4]
The field with value 123, gets output as 123.000000. Can something be done about that?

**Comment by pteich** [comment]
Yes, I'm not sure why I added a different formatting depending on the data type some times ago. If we just stick with the default formatting for every Go type it will result in exact this behaviour. I'll change this.

**Comment by brablc** [comment]
May be you wanted to avoid scientific format (before fix | after fix):

```
107327.000000,4554.000000,0.000000			      |	107327,4554,0
107327.000000,7521.000000,0.000000			      |	107327,7521,0
108051.000000,1174889.000000,1147.782000		      |	108051,1.174889e+06,1147.782
108051.000000,1254914.000000,1227.949000		      |	108051,1.254914e+06,1227.949
108051.000000,1255122.000000,1215.071000		      |	108051,1.255122e+06,1215.071
```

**Comment by pteich** [comment]
I'll create a new release that includes the fix from @dinhtrung
