### ISSUE TITLE
Do not disclose credentials upon unsuccessful login

### ISSUE THREAD

**Issue by brablc** [pteich/elastic-query-export#7]
When connecting using `es-query-export -c "http://username:password@localhost:9200"` the password is leaked when server is not available:

```
2021/11/02 13:50:42 Error connecting to ElasticSearch http://username:password@localhost:9200/ - elastic: Error 401 (Unauthorized)
```

Would it be possible to hide the password? Or is there any possibility to use entry from .netrc (as in `curl --netrc-file /root/.netrc`)?

**Comment by pteich** [comment]
I've changed the output in case of an error as the underlying library mentioning the host anyway (and hides the password)

```
2021/11/03 19:47:39 Error connecting to ElasticSearch: health check timeout: Head "http://username:***@localhost:9200": dial tcp [::1]:9200: connect: connection refused: no Elasticsearch node available
```
I've creating a new release for this.

Regarding .netrc - this should be possible, I'll have a look at it.

**Comment by brablc** [comment]
The error message is great when node does not respond, in case when username / password is incorrect the message is somewhat short:

```
2021/11/04 16:12:25 Error connecting to ElasticSearch: elastic: Error 401 (Unauthorized)
```
