### ISSUE TITLE
Can you support exporting json format

### ISSUE THREAD

**Issue by kerven88** [pteich/elastic-query-export#8]
Can you support exporting json format?
One line of json data, like the following：
![image](https://user-images.githubusercontent.com/51351006/142836565-4caf9905-72f3-4db1-b522-44021eeaeb9c.png)

**Comment by pteich** [comment]
Yes, this should be possible without too much effort. I'll try to get my hands on this within the next couple of days.

**Comment by pteich** [comment]
@kerven88 I've added the output format you've requested as `raw`. However there is another new format named `json` that only exports the document data (all or selected fields). The `raw` format does always a full dump of the document including metadata, one document per line.
